kleaf: Fix ScmversionIntegratonTest when running locally.
Because PYTHONPATH and PYTHONSAFEPATH is set, workspace_status_stamp.py
cannot run repo properly with the error

  ModuleNotFoundError: No module named 'color'

Drop PYTHONSAFEPATH.

Fixes: 288334980
Bug: 288334980
Test: manually run test locally
Change-Id: I4484117caedccd07d0e4378acdaeb4e4fbd27eef